### ISSUE TITLE
Update to Elm 0.18?

### ISSUE THREAD

**Issue by justgage** [danyx23/elm-dropzone#4]
This looks like a cool library. I think it would be cool to update this to the latest version of Elm (if possible). Don't feel pressured to do it immediately, I'm just making an issue to track this.

**Comment by justgage** [comment]
I read the README a little more carefully, seems like it's not possible yet?

**Comment by dawehner** [comment]
I just tried to port the example to elm 0.18 and it seems to totally work after the PR in #5

**Comment by justgage** [comment]
👏👏👏👏

**Comment by dawehner** [comment]
🎆🎆🎆 :)

**Comment by danyx23** [comment]
Thanks everyone & sorry it took a little longer this time!
